### Register for user
POST http://localhost:4000/auth-api/register
Content-Type: application/json

{
    "name": "Dukudu Navadeep", 
    "email": "navadeep@gmail.com",
    "password": "12345", 
    "role": "expert"
}

### Login for user
POST http://localhost:4000/auth-api/login 
Content-Type: application/json

{
    "email": "rishivar.d@gmail.com", 
    "password": "12345"
}

### Create or update expert
POST http://localhost:4000/expert-api/experts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmI0NGU4YTQyMmU3N2U3OGFhNDM1OSIsInJvbGUiOiJleHBlcnQiLCJpYXQiOjE3NDQ1MjA0MzcsImV4cCI6MTc0NTEyNTIzN30.oiikDtDs_KQvMZhgpUWEcJmtIJiP-ptOBfcrr9iFzSE

{
    "bio": "Certified career coach helping students navigate job interviews.",
    "domain": "Health",
    "price": 500,
    "availability": ["Tuesday 16:00-18:00", "Friday 10:00-12:00"],
    "tags": ["Help", "Physical", "Mental"]
}

### Get all experts by using filter
### expert?domain=Web%20Development&minPrice=30&maxPrice=100&tag=React
GET http://localhost:4000/expert-api/expert

### Get expert by id
GET http://localhost:4000/expert-api/expert/67fb4397a422e77e78aa433f

### Book an appointment
POST http://localhost:4000/booking-api/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE0OTI2YTQxNzQxMDIzOGMwZjYxMSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NTI2OTc5LCJleHAiOjE3NDUxMzE3Nzl9.SiCFSrZ38nrcxklpLGjWqFZLAdBZ_E7rpXs3FF0LrI0

{
    "expertId": "67fb4397a422e77e78aa433f", 
    "date": "2025-04-15", 
    "Time":"12 PM - 1 PM"
}

### Get all user bookings
GET http://localhost:4000/booking-api/user-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE0OTI2YTQxNzQxMDIzOGMwZjYxMSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NTI2OTc5LCJleHAiOjE3NDUxMzE3Nzl9.SiCFSrZ38nrcxklpLGjWqFZLAdBZ_E7rpXs3FF0LrI0

### Get all expert bookings
GET http://localhost:4000/booking-api/expert-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE0OTNlYTQxNzQxMDIzOGMwZjYxNyIsInJvbGUiOiJleHBlcnQiLCJpYXQiOjE3NDQ1MjcxMzUsImV4cCI6MTc0NTEzMTkzNX0.BJfIvaKuRcufmjE7vKwIdxC5E_Ksj3ph-YfYcKNmz40

###Get all bookings done by an expert using expert Id
GET http://localhost:4000/booking-api/avail-bookings/67fb4397a422e77e78aa433f

###Get all timings which are available by using expertId and date
GET http://localhost:4000/booking-api/timings/67fb4397a422e77e78aa433f/2025-04-15