### Register for user
POST http://localhost:4000/auth-api/register
Content-Type: application/json

{
    "name": "sharath", 
    "email": "karthikgajavelly@gmail.com",
    "password": "12345", 
    "role": "expert"
}

### Login for user
POST http://localhost:4000/auth-api/login 
Content-Type: application/json

{
    "email": "karthikgajavelly001@gmail.com", 
    "password": "12345"
}

### Create or update expert
POST http://localhost:4000/expert-api/experts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE3MWM0MGVmZGNhMjAyZmRhMzZlNSIsInJvbGUiOiJleHBlcnQiLCJpYXQiOjE3NDQ0NjY2MzcsImV4cCI6MTc0NTA3MTQzN30.mUs6GIq3cnC31B4_NXWxDPnhY34eBxSWbfFFx6IaU_I

{
    "userId": "67fa71c40efdca202fda36e5",
    "bio": "Certified career coach helping students navigate job interviews.",
    "domain": "Career Coaching",
    "price": 3000,
    "availability": ["Tuesday 16:00-18:00", "Friday 10:00-12:00"],
    "tags": ["Resume", "Interview", "Job Search"]
}

### Get all experts by using filter
### expert?domain=Web%20Development&minPrice=30&maxPrice=100&tag=React
GET http://localhost:4000/expert-api/expert

### Get expert by id
GET http://localhost:4000/expert-api/expert/67fa73f30efdca202fda36ea

### Book an appointment
POST http://localhost:4000/booking-api/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE2OTVlOWY5Y2M3NzNhMTQ3Zjg5YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NDY5OTc1LCJleHAiOjE3NDUwNzQ3NzV9.Q7ch1uF-Vmvo4rmjKDi2n-EJAlPMzTMcpfPRvcIXA_4

{
    "expertId": "67fa73f30efdca202fda36ea", 
    "date": "2025-04-15", 
    "time": "15:00"
}

### Get all user bookings
GET http://localhost:4000/booking-api/user-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE2OTVlOWY5Y2M3NzNhMTQ3Zjg5YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NDY5OTc1LCJleHAiOjE3NDUwNzQ3NzV9.Q7ch1uF-Vmvo4rmjKDi2n-EJAlPMzTMcpfPRvcIXA_4

### Get all expert bookings
GET http://localhost:4000/booking-api/expert-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE2OTVlOWY5Y2M3NzNhMTQ3Zjg5YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NDY5OTc1LCJleHAiOjE3NDUwNzQ3NzV9.Q7ch1uF-Vmvo4rmjKDi2n-EJAlPMzTMcpfPRvcIXA_4